language: node_js
node_js:
    "node"
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - npm run dist
  - ls dist/*

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file:
      - "dist/btcpmine*.AppImage"
      - "dist/dist/btcpmine*.snap"
  skip_cleanup: true
  on:
    tags: true
