platform: x64

skip_tags: true

environment:
  nodejs_version: "8"

branches:
  only:
    - master
  except:
    - dev

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start
  # install modules
  - rm package-lock.json
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Show home directory
  - node -p "os.homedir()"
  # Run tests
  - npm test

build_script:
  # Build Windows binary
  - npm run dist
  - ls dist

artifacts:
  - path: 'dist\squirrel-windows\btcpmine*OneClick*.exe'
    name: btcpmine

deploy:
    release: btcpmine-v$(appveyor_build_version)
    description: '# BTCPMine - One click miner for Bitcoin Private'
    provider: GitHub
    auth_token:
        secure: Na6qvldBSW67WV2t5VXL94Zx49sjmcfcmYhwtjDPeozxMIJhYIA4X7GE7oPig8fK
    artifact: btcpmine
    draft: true
    prerelease: false
    on:
        branch: master                # release from master branch only
        appveyor_repo_tag: false      # deploy on tag push only

# Don't actually build.
#build: off
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
